controller_list:
  - name: fake_manipulator_controller
    joints:
      - ur5/shoulder_pan_joint
      - ur5/shoulder_lift_joint
      - ur5/elbow_joint
      - ur5/wrist_1_joint
      - ur5/wrist_2_joint
      - ur5/wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_finger1_joint